### ISSUE TITLE
V2 Broken

### ISSUE THREAD

**Issue by KaidKM3** [Kyryh/WesV2#1]
Once i installed the mod. it broke the AI on V2. The 1-4 it will not shoot at all. apon defeating V2 in 1-4 it breaks. it will not move. shooting him with a slab revolver causes a broken tracer, coins when shot at v2 break gravity and apon shooting again it would work like normal but ignoring v2. Also the voice line doesnt play during the intro to the duel. but the sliding by moment when you collect the first skull voice plays.

4-4. V2 in 4-4 can fire its piercer to shoot the coins you throw. everything else is broken. the second phase of the battle he gets stuck in the exit and doesnt break.

Here is the Logs to figure out what is breaking.
[LogOutput.log](https://github.com/Kyryh/WesV2/files/14103190/LogOutput.log)

**Comment by Kyryh** [comment]
It probably broke with the recent updates, I'll have a look soon

**Comment by Kyryh** [comment]
Fixed with 2bc0024, will publish an update soon

**Comment by KaidKM3** [comment]
Okay.
